### ISSUE TITLE
Thread Safety

### ISSUE THREAD

**Issue by drmnick** [active-hash/active_hash#159]
Wrote simplistic example to evaluate below: 

```ruby
require 'active_hash'
class Item < ActiveYaml::Base
end
@thr = []
def f(i) 
    @thr << Thread.new { puts 'Thread ' + i.to_s + ': ' + Item.all.length.to_s }
end
for i in 0..5
    f i
end
@thr.each(&:join)
``` 

Most of the time output is `Thread 5: 4, Thread 0: 4, Thread 3: 4, Thread 2: 4, Thread 1: 4, Thread 4: 4` with different thread ordering, but sometimes I see `Thread 3: 0, Thread 2: 0, Thread 4: 0, Thread 1: 0
, Thread 0: 4, Thread 5: 4` 

I have `items.yml` file in the root with 4 items `- val: 1`. My `Gemfile.lock` shows the `active_hash (1.5.3)` which I suppose is the latest.

I would expect for library to guarantee thread safety.

**Comment by amclelland** [comment]
Running into problems using Active Hash with Sidekiq and we think it might be related to this issue

**Comment by berniechiu** [comment]
> Running into problems using Active Hash with Sidekiq and we think it might be related to this issue.

Getting ActiveHash::RecordNotFound every so often

@amclelland We've encountered this too, any idea for a temp solution?

**Comment by umeldt** [comment]
A quick fix is to force ActiveHash to read the models as soon as possible, for example by calling the `.all` class method after the of the class definition:

```ruby
require 'active_hash'
class Item < ActiveYaml::Base
end
Item.all
@thr = []
def f(i) 
    @thr << Thread.new { puts 'Thread ' + i.to_s + ': ' + Item.all.length.to_s }
end
for i in 0..5
    f i
end
@thr.each(&:join)
```
