### ISSUE TITLE
Using ActiveHash::Associations and JSONAPISerializer at the same time will result NoMethodError.

### ISSUE THREAD

**Issue by 1160054** [active-hash/active_hash#236]
<img width="1035" alt="スクリーンショット 2021-09-26 18 50 29" src="https://user-images.githubusercontent.com/9334235/134802867-03c94db6-e7f7-43df-88a1-4ba829a0ebb9.png">

# Controller
<img width="646" alt="スクリーンショット 2021-09-26 19 00 26" src="https://user-images.githubusercontent.com/9334235/134803192-1814e3a3-be33-4d81-8d51-f1ad3f15ea0e.png">

# Model
<img width="641" alt="スクリーンショット 2021-09-26 18 55 05" src="https://user-images.githubusercontent.com/9334235/134803017-c3436b6b-8f1e-4605-9413-b31130849e95.png">

# Seriralizer
<img width="832" alt="スクリーンショット 2021-09-26 19 01 44" src="https://user-images.githubusercontent.com/9334235/134803244-0f7bd8b8-6d5c-4f8e-aecb-7ee48e83d736.png">

# How to fix
## Pattern 1
<img width="524" alt="スクリーンショット 2021-09-26 18 56 01" src="https://user-images.githubusercontent.com/9334235/134803020-81553fe9-d69d-4f88-9a00-00e82993d4fa.png">

## Pattern 2 
<img width="641" alt="スクリーンショット 2021-09-26 18 57 31" src="https://user-images.githubusercontent.com/9334235/134803076-896d3a02-31ca-4ddb-bb6e-dd80e3c3cf4f.png">

**Comment by kbrock** [comment]
think this is fixed.

Let me know if there is still an issue here.
