### ISSUE TITLE
Rails 7 Compatibility

### ISSUE THREAD

**Issue by adampal** [active-hash/active_hash#252]
The test suite fails when run against Rails 7.
It seems there have been some breaking changes introduced in ActiveRecord.

Some more discussion here:
https://github.com/active-hash/active_hash/issues/249

**Comment by Idletime-studios** [comment]
Was just following up on this. 

I have tried most recent released version and it doesn't seem to work as expected.  example: search for id 6, and return result for id 2

Any ideas?

**Comment by adampal** [comment]
@Idletime-studios there is a fix in the works here:
https://github.com/active-hash/active_hash/pull/267

**Comment by kbrock** [comment]
Looks like this has all been merged. Holler if I am wrong here.

**Comment by jmartyniak** [comment]
@kbrock @adampal i will check it tomorrow.  Thank you!
