### ISSUE TITLE
Make releases more often?

### ISSUE THREAD

**Issue by andreynering** [active-hash/active_hash#253]
The latest release was a long time ago, on January 2020, so about 2 and half years ago.

Although it is possible to import gems via GitHub, most people will really use the tagged version via Ruby Gems.

Having more frequent releases would be awesome so people would be really benefiting from the most recent changes.

**Comment by adampal** [comment]
I agree.  I think this gem has been fairly stagnant for a while. I'm hoping we can get it moving again now we've got GH Actions happening for CI so we can release with more confidence.

**Comment by adampal** [comment]
@andreynering New release just published to RubyGems now.
